---
  - hosts: all
    tasks:
        - name: Install HAProxy
          apt: pkg=haproxy state=installed update-cache=true
          notify:
              - restart haproxy
    handlers:
      - name: restart haproxy
        service:
          name: haproxy
          state: restarted
